services:
  db:
    image: postgres:15
    container_name: tour_de_controle_db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5433:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - tour_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 30s
      timeout: 10s
      retries: 5

  sqitch:
    image: sqitch/sqitch
    container_name: tour_de_controle_sqitch
    volumes:
      - ./db/migrations:/project
      - ./db/scripts/wait-for-it.sh:/wait-for-it.sh
    depends_on:
      - db
    working_dir: /project
    entrypoint: >
      /bin/bash -c "
      /wait-for-it.sh db:5432 --
      sqitch deploy db:pg://${SQITCH_USER}:${SQITCH_PASSWORD}@db:5432/${SQITCH_DB} &&
      sqitch verify db:pg://${SQITCH_USER}:${SQITCH_PASSWORD}@db:5432/${SQITCH_DB}
      tail -f /dev/null
      "
    networks:
      - tour_network

  backend:
    build: ./backend
    container_name: tour_de_controle_backend
    restart: always
    environment:
      DATABASE_URL: postgres://admin:admin123@db:5432/tour_de_controle
    ports:
      - "4000:4000"
    depends_on:
      - db
    networks:
      - tour_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4000/health"]
      interval: 30s
      timeout: 10s
      retries: 5

  frontend:
    build: ./frontend
    container_name: tour_de_controle_frontend
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - tour_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 5

  swagger:
    image: swaggerapi/swagger-ui
    container_name: tour_de_controle_swagger
    ports:
      - "8080:8080"
    environment:
      SWAGGER_JSON: /swagger/swagger.json
    volumes:
      - ./backend/docs/swagger:/swagger
    networks:
      - tour_network

  pgadmin:
    image: dpage/pgadmin4
    container_name: tour_de_controle_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@tour.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8081:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - db
    networks:
      - tour_network

volumes:
  db_data:
  pgadmin_data:

networks:
  tour_network:
      driver: bridge