[core]
    engine = pg
[engine "pg"]
    target = db:pg://admin:admin123@localhost:5432/tour_de_controle
    registry = sqitch
    client = psql
    username = admindb
    password = adm1n
    deploy_dir = migrations/deploy
    revert_dir = migrations/revert
    verify_dir = migrations/verify